credentials:
  usernames:
    gagan:
      email: gagan@gmail.com
      name: gagan
      password: abc # To be replaced with hashed password
    guri:
      email: guri@gmail.com
      name: gurminder
      password: def # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com